### PR TITLE
Example application

### PR DESCRIPTION
**Pull request by oddjobz**
This is a sample application to demonstrate the use of;

- Client side TLS certificate authentication
- Round robin registration for  HA
- Dynamic authorization
- Dynamic  authentication
- Handing dynamic auth's off to separate processes
- Connecting  to multiple realms

### CODE REVIEW

**Comment by oberstet** [comment]
awesome! actually, an example of a more complex application base with AA. Nice. I think this really helps devs getting beyond the getting started phase.

Only thing I spotted: Pipfile.lock => is that required?

**Comment by oberstet** [comment]
2 more thoughts:

- we should link to these examples from the CB docs too .. in general: discoverability
- we should discuss how to go forward with the 3 places where CB examples reside: crossbar-examples, iotcookbook and cookiecutters

**Comment by oddjobz** [comment]
Mmm, no, goot point, you can re-generate Pipfile.lock with "pipenv lock", so it could be removed and "pipenv lock" added to the build instructions .. hadn't occurred to me will amend .. :)

**Comment by oddjobz** [comment]
Incidentally, one thing I was a little concerned about were the "make_*_ssl.py routines in "utils" .. these work fine, but my knowledge of encryption technologies is limited and more based on example than actual knowledge, so if I'm doing anything in here that's sub-optimal (or insecure!) a more knowledgeable pair of eyes would me much appreciated .. :)

**Comment by oberstet** [comment]
yeah, `app/generic-crossbar-app/utils/make_client_ssl.py` and `app/generic-crossbar-app/utils/make_server_ssl.py` .. this isn't the "recommended way", and likely has some detail issues (not that I see any on first spot, but .. this cert stuff is terrible hard to get right).  so there is a thing called the Twisted endpoints API. and then @meejah , I guess if this is to be used as a template for users to follow, what would be the recommended way from AB using components and respective runner?

**Comment by oddjobz** [comment]
Mmm, I know this can be done with bash / openssl, and I think I started out this way, but after doing this in production and having to automatically generate and refresh keys then inject them into a dynamic authentication system, I found this much easier in an all-Python environment. (much of the example code is based on previous projects .. in production the server cert was via LetsEncrypt, so only the client code was actually used ...)

Might be interesting to present both options (?) , but if there's any way to validate the Python method, that would be cool.

**Comment by oberstet** [comment]
you can find a complete example that includes TLS cert generation etc using openssl here: https://github.com/crossbario/crossbar-examples/tree/master/encryption/tls

**Comment by oddjobz** [comment]
Ok, so .. I'm seeing 160 lines of shell script .. containing the comment "Whew!! We've made a CA, and an intermediate CA!" .. it's starting to come back to me now .. I think this is why it took me so long to start using client TLS certificates .. and why I coded it in Python .. please could we consider "a" Python approach as the recommended method? Putting myself back into a "user" mindset, it may be the recommended technical approach, but I don't think it's appealing from a developer's perspective ...

**Comment by oberstet** [comment]
first, fully agreed: setting up CA/cert stuff with plain openssl is tedious and error prone .. and I forget most of it anyways again.

here is what I think:

* having a super simple to use Lets Encrypt based cert thing in CB would be great!
* building a Python based full blown CA management solution: not our focus exactly ..

> "a" Python approach as the recommended method?

what if I am a C++ dev using ABC++, and CB as a blackbox?

**Comment by oddjobz** [comment]
Mm, in this instance the example is pure Python .. so I guess this depends on whether you would envisage porting the example into (n) languages. The example is contextually one way to do it "in Python", I wouldn't envisage discounting or dropping other alternatives or documentation .. that said, I'm just wondering whether it might be useful to have an 'issue client certificate' call built into CB/CF/CFC somewhere.. going just a little further, I've noticed some platforms are now integrating LetsEncrypt and doing certificate acquire and renew as a default back-end function ... i.e. it would be relatively easy to build all key management into Crossbar by default .. then you only have to fiddle if you want your own non-LetsEncrypt SSL cert ... then the issue of shell scripts of implementing stuff in other languages, all goes away .. (?)

**Comment by meejah** [comment]
My experience so far with "pipfile" / "pipenv" is **terrible**. Making it work in e.g. a virtualenv was a giant pain; not sure if it's a good idea to use "for real" quite yet?

As for the certificates stuff: that shell script was "mostly" for completeness (i.e. to show how I made a "for testing" CA-signed certificate). I wouldn't expect most developers to ever need to set up their own CA etc -- "just use Let's Encrypt" should be the route for most people. (And yes, having an easier way to use Let's Encrypt in CB would be good)

Of course, if you're going to do client-side TLS certificates, then you *are* a CA -- but anyone doing this likely already has some infrastructure in place. So, I don't particularly see a lot of value in doing this "in Python" since I'd imagine the people actually doing that are most likely to use Bash?

**Comment by meejah** [comment]
As for "endpoints", yes that would be the preferred route in Twisted. Mostly the Twisted defaults are secure (or are supposed to be) -- so I'd personally try to do away with all the weird options (e.g. selecting ciphers and so on) and "just use the defaults" as provided by Twisted/CB.

**Comment by oberstet** [comment]
@oddjobz 

> it would be relatively easy to build all key management into Crossbar by default .. then you only have to fiddle if you want your own non-LetsEncrypt SSL cert ... then the issue of shell scripts of implementing stuff in other languages, all goes away .. (?)

yep!

the problem is automating lets encrypt when running multiple nodes behind a LB. each node should have an own private key, and a cert with the dedicated name (cn) and the shared common name in addition in the cert.

eg, the only way I found in our setup for demo.crossbar.io is via DNS verification, and that means dynamically reconfiguring a zone. In our case, the zone is hosted on Route 53. Hence, CFC would need to talk to AWS Route 53 .. but we actually could make use of that (CFC being able to talk to AWS via their REST API) for proxy workers and clustering: when a proxy worker dies or is added (a frontend), the AWS ELB needs to know that. ELB will detect an unresponsive backend itself, I guess also when it comes back, but probably not quickly, and the initial set of backends needs to be setup as well.

So a feature like the following would be of high practical use IMO:

* lets encrypt based certs for CF nodes
* automated via CFC
* integrated with AWS

**Comment by oddjobz** [comment]
Re; Twisted endpoints, I'm not sure I understand the significance, don't you still need to have certificates, is this not just an alternative socket API?

Re; pipenv, I moved over to it a year ago, it's not given me any reason to look back. Would be interested to see if it causes a problem with anyone re; building the demo.

With regards to letsencrypt etc, I think this would be a really useful / popular feature, esp. if we chain client certificate issuing off the back .. there seem to be half a dozen letsencrypt python libraries out there, not sure what state they're in, but it looks like others have the same idea. I know it's been built into mail-in-a-box for the last year or so .. I never have to worry about my mail-server's cert expiring .. :)

Re; Pipenv ...
http://docs.python-guide.org/en/latest/dev/virtualenvs/
http://howtopython.org/en/latest/getting-started/

**Comment by oberstet** [comment]
> there seem to be half a dozen letsencrypt python libraries out there

which of these support DNS based verification and can talk to route53? actual, I am -1 on adding anything but DNS based verification (from CFC) .. eg regular HTTP based verification. wont work behind LB, wont work when running on edge devices, and those are core scenarios for CB.

**Comment by oddjobz** [comment]
Ok, well, I've not played with this before but it looks like;

- https://github.com/Trim/acme-dns-tiny
- https://github.com/adfinis-sygroup/acme-powerdns

Having said that, the code looks relatively trivial .. might be Ok to see if this works, but I'm not overly impressed by the quality of the code .. might be inclined to write something a little more robust ..

**Comment by oberstet** [comment]
@oddjobz I'Ve had a quick look into the 2 repos you linked: yeah, same impression here .. this looks quite "ad hoc", and we might be better off just write sth ourself.

---

FWIW, short description of how LE DNS based verification works:

"""
When the client requests a certificate, the CA asks the client to prove ownership over the domain by adding a specific TXT record to its DNS zone. More specifically, the CA sends a unique random token to the ACME client, and whoever has control over the domain is expected to put this TXT record into its DNS zone, in the predefined record named "_acme-challenge" under the actual domain the user is trying to prove ownership of. As an example, if you were trying to validate the domain for *.eff.org, the validation subdomain would be "_acme-challenge.eff.org." When the token value is added to the DNS zone, the client tells the CA to proceed with validating the challenge, after which the CA will do a DNS query towards the authoritative servers for the domain. If the authoritative DNS servers reply with a DNS record that contains the correct challenge token, ownership over the domain is proven and the certificate issuance process can continue.
"""

https://www.eff.org/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation

This article is also highly interesting because it discusses an obvious weak spot in the overall big picture: DNS zones

A compromise is absolutely deadly and largely unlimited in resulting scope: once an attacker got your zone, he can take over _everything_ ..

---

or, we could build the following into cfc:

* https://twistedmatrix.com/documents/current/names/
* https://twistedmatrix.com/documents/current/names/howto/custom-server.html

store the zone info in zlmdb inside cfc node controller, and directly integrate LE into that. with that, we could make LE based TLS work completely automated - on every cloud. since it comes with batteries includes (Twisted Names for authorative DNS)

**Comment by meejah** [comment]
For "Let's Encrypt" the thing to use is ``txacme`` which implements both sides of the ACME protocol. We can already "just drop this in" right now with zero CB changes: use an endpoint-string like ``"le:/path/to/where/certs/are/stores"``. https://txacme.readthedocs.io/en/stable/

For "real" support we'd add some configuration options (e.g. ``"endpoint": {"type": "lets_encrypt"}``). The only downside here is that you have to be able to listen on 80 and 443 (80 for the challenges).

**Comment by meejah** [comment]
@oberstet yes a "real" non-trivial example using components and TLS would be good. Every time I look at the autobahn-python examples, I want to rototill the whole thing -- so would be good to I think do two things:

 - simplify (i.e. condense the examples into fewer)
 - convert to ``component`` + ``run`` for all (most) examples
 - leave at least one ``ApplicationRunner`` / "legacy" thing for posterity

By "condense" I mean e.g. taking most of the pubsub variants and putting them in "one" example (e.g. so you can read through it and see "here's a basic sub + pub" then one with "options" use, etc).

**Comment by meejah** [comment]
@oddjobz: " i.e. it would be relatively easy to build all key management into Crossbar by default ."

Yeah, this is what "txacme" does. Right now you can use it via the "endpoints" APIs (which, yes, are "just" the nice Twisted interface for Twisted socket-stuff).

**Comment by oddjobz** [comment]
@meejah Ok, that sounds pretty cool .. will take a look :)

**Comment by oberstet** [comment]
more notes:

* https://txacme.readthedocs.io/en/stable/api/txacme.challenges.html?highlight=dns#txacme.challenges.LibcloudDNSResponder

=> "Some libcloud backends are broken with regard to TXT records at the time of writing; the Route 53 backend, for example. This makes them unusable with this responder."

Not sure what that means. txacme in principle supports DNS based verification with LE and also Route 53, but there is a bug?

* I guess supporting SNI also plays into here .. which we dont currently

**Comment by meejah** [comment]
sounds like is (or will be soon) fixed for route53: https://github.com/twisted/txacme/issues/120

**Comment by oddjobz** [comment]
@oberstet @meejah I think the LetsEncrypt idea is a really good one and at the very least worth a little more scrutiny, should we move the discussion to a ticket somewhere as it's unlikely to be a part of this demo in the near term ?  :)

**Comment by meejah** [comment]
Regarding Let's Encrypt, see also: https://github.com/crossbario/crossbar/issues/1124 and https://github.com/crossbario/crossbar/issues/1123

**Comment by oberstet** [comment]
> should we move the discussion to a ticket somewhere

yeah, good idea! on crossbario/crossbarfx, and cross-linking all the stuff above in this one place .. useful as a shared reference.

**Comment by oddjobz** [comment]
Ok, 18 days and counting .. unless I'm missing something I've no concrete changes to make and nobody has approved the PR.

**Pull request merged**
